version: '3.9'

services:
  social-backend-dev:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    container_name: social-backend-dev
    image: social-backend-dev
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis
    networks:
      - social-network-dev
    volumes:
      - .:/code

  db:
    image: postgres:latest
    container_name: db
    networks:
      - social-network-dev
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - social-network-dev
