version: "3.9"

services:

  web:
    build:
      context: .
      target: base
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/index.js"]

  redis:
    image: redis
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt