services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
