version: "3.9"

services:
 backend:
    build:
      context: backend
      target: development
    secrets:
      - db-password
    depends_on:
      - db
 redis:
    image: redis
    depends_on: 
      - db
 db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data:

