services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80

  social-backend:
    image: social-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
