version: '3'

services:
  social-backend-staging:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: social-backend-staging
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis
    networks:
      - social-network-staging
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ['./wait-for-postgres.sh', 'db:5432', '--', 'node', 'index.js']

  db:
    image: postgres:latest
    networks:
      - social-network-staging
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis/redis-stack-server
    networks:
      - social-network-staging

networks:
  social-network-staging:
